# Collaboration and Competition

---

You are welcome to use this coding environment to train your agent for the project.  Follow the instructions below to get started!

### 1. Start the Environment

Run the next code cell to install a few packages.  This line will take a few minutes to run!

In [1]:
!pip -q install ./python

The environment is already saved in the Workspace and can be accessed at the file path provided below. 

In [3]:
from unityagents import UnityEnvironment
import numpy as np

env = UnityEnvironment(file_name="/data/Tennis_Linux_NoVis/Tennis")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [4]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

Run the code cell below to print some information about the environment.

In [5]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents 
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 2
Size of each action: 2
There are 2 agents. Each observes a state with length: 24
The state for the first agent looks like: [ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.         -6.65278625 -1.5        -0.          0.
  6.83172083  6.         -0.          0.        ]


In [12]:
from collections import namedtuple, deque

In [13]:
def transpose_to_tensor(input_list):
    make_tensor = lambda x: torch.tensor(x, dtype=torch.float)
    return list(map(make_tensor, zip(*input_list)))

In [14]:
experience = namedtuple("Experience", field_names=["state", "action", "reward", "next_state", "done"])

In [15]:
actions = np.random.randn(num_agents, action_size)
rewards = env_info.rewards
next_states = env_info.vector_observations
dones = env_info.local_done

In [16]:
memory = deque(maxlen=50)
for i in range(15):
    e = experience(states, actions, rewards, next_states, dones)
    memory.append(e)

In [17]:
state_buffer = torch.from_numpy(np.array([random.sample(memory, k=3)[0].state,
                          random.sample(memory, k=3)[0].state,
                          random.sample(memory, k=3)[0].state]))
state_buffer.shape

torch.Size([3, 2, 24])

In [45]:
state_buffer

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000, -6.6528, -1.5000, -0.0000,  0.0000,  6.8317,
           6.0000, -0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000, -6.4670, -1.5000,  0.0000,  0.0000, -6.8317,
           6.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000, -6.6528, -1.5000, -0.0000,  0.0000,  6.8317,
           6.0000, -0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000, -6.4670, -1.5000,  0.0000,  0.0000, -6.8317,
        

In [29]:
state_buffer[:,0,:]

torch.Size([3, 24])

In [124]:
state_buffer[:,0,:].shape

torch.Size([3, 24])

In [24]:
action_buffer = torch.from_numpy(np.array([random.sample(memory, k=3)[0].action,
                          random.sample(memory, k=3)[1].action,
                          random.sample(memory, k=3)[0].action]))
action_buffer.shape

torch.Size([3, 2, 2])

In [28]:
action_buffer = torch.from_numpy(np.array([np.random.standard_normal((2,2)),
                          np.random.standard_normal((2,2)),
                          np.random.standard_normal((2,2))]))
action_buffer.shape

torch.Size([3, 2, 2])

In [29]:
action_buffer

tensor([[[ 1.0354, -0.7481],
         [-1.2943,  0.1369]],

        [[-0.8765,  0.1402],
         [-0.8344,  0.1745]],

        [[-2.8626,  1.8260],
         [-0.8555, -0.1743]]], dtype=torch.float64)

In [30]:
action_buffer.view(-1,4)

tensor([[ 1.0354, -0.7481, -1.2943,  0.1369],
        [-0.8765,  0.1402, -0.8344,  0.1745],
        [-2.8626,  1.8260, -0.8555, -0.1743]], dtype=torch.float64)

In [31]:
torch.reshape(action_buffer,(3,4))

tensor([[ 1.0354, -0.7481, -1.2943,  0.1369],
        [-0.8765,  0.1402, -0.8344,  0.1745],
        [-2.8626,  1.8260, -0.8555, -0.1743]], dtype=torch.float64)

In [33]:
action_buffer = torch.stack([torch.cat([action for action in epi]) for epi in action_buffer])
action_buffer.shape

torch.Size([3, 4])

In [35]:
torch.cat((state_buffer[:,0,:],action_buffer), dim = 1).shape

torch.Size([3, 28])

In [118]:
action_buffer

tensor([[[-2.3465,  0.6334],
         [-2.1670,  1.3852]],

        [[-2.3465,  0.6334],
         [-2.1670,  1.3852]],

        [[-2.3465,  0.6334],
         [-2.1670,  1.3852]]], dtype=torch.float64)

In [20]:
reward_buffer = torch.from_numpy(np.array([random.sample(memory, k=3)[0].reward,
                          random.sample(memory, k=3)[0].reward,
                          random.sample(memory, k=3)[0].reward]))
reward_buffer.shape

torch.Size([3, 2])

In [26]:
random_mat = torch.from_numpy(np.random.rand(3,2))
random_mat

tensor([[ 0.1836,  0.2703],
        [ 0.7944,  0.6573],
        [ 0.5889,  0.1961]], dtype=torch.float64)

In [29]:
torch.max(random_mat, dim = 1)[0]

tensor([ 0.2703,  0.7944,  0.5889], dtype=torch.float64)

In [133]:
action_buffer

tensor([[-2.3465,  0.6334, -2.1670,  1.3852],
        [-2.3465,  0.6334, -2.1670,  1.3852],
        [-2.3465,  0.6334, -2.1670,  1.3852]], dtype=torch.float64)

In [135]:
torch.cat((state_buffer[:,0,:],action_buffer), dim = 1).shape

torch.Size([3, 28])

In [115]:
torch.reshape(test,(3,48))

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000, -6.6528, -1.5000, -0.0000,  0.0000,  6.8317,
          6.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -6.4670, -1.5000,
          0.0000,  0.0000, -6.8317,  6.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000, -6.6528, -1.5000, -0.0000,  0.0000,  6.8317,
          6.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -6.4670, -1.5000,
          0.0000,  0.0000, -6.8317,  6.0000,  0.0000,  0.0000],
        

In [11]:
test = np.arange(10).reshape(-1,2)
test

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
np.max(test.sum(axis = 0))

25

### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Note that **in this coding environment, you will not be able to watch the agents while they are training**, and you should set `train_mode=True` to restart the environment.

In [12]:
for i in range(5):                                         # play game for 5 episodes
    env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
    states = env_info.vector_observations                  # get the current state (for each agent)
    scores = np.zeros(num_agents)                         # initialize the score (for each agent)
    while True:
        actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
        actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
        env_info = env.step(actions)[brain_name]           # send all actions to tne environment
        next_states = env_info.vector_observations         # get next state (for each agent)
        rewards = env_info.rewards                         # get reward (for each agent)
        dones = env_info.local_done                        # see if episode finished
        scores += env_info.rewards                         # update the score (for each agent)
        states = next_states                               # roll over states to next time step
        if np.any(dones):                                  # exit loop if episode finished
            break
    print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

Total score (averaged over agents) this episode: -0.004999999888241291
Total score (averaged over agents) this episode: -0.004999999888241291
Total score (averaged over agents) this episode: -0.004999999888241291
Total score (averaged over agents) this episode: -0.004999999888241291
Total score (averaged over agents) this episode: -0.004999999888241291


When finished, you can close the environment.

In [ ]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  A few **important notes**:
- When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```
- To structure your work, you're welcome to work directly in this Jupyter notebook, or you might like to start over with a new file!  You can see the list of files in the workspace by clicking on **_Jupyter_** in the top left corner of the notebook.
- In this coding environment, you will not be able to watch the agents while they are training.  However, **_after training the agents_**, you can download the saved model weights to watch the agents on your own machine! 

In [1]:
import random
import torch
import numpy as np
from collections import deque
import matplotlib.pyplot as plt
from unityagents import UnityEnvironment
%matplotlib inline

from maddpg import MADDPG

In [2]:
env = UnityEnvironment(file_name="Tennis_Linux/Tennis.x86_64")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]
env_info = env.reset(train_mode=True)[brain_name]
num_agents = len(env_info.agents)
action_size = brain.vector_action_space_size
states = env_info.vector_observations
state_size = states.shape[1]

In [4]:
maddpg_agent = MADDPG(num_agents=num_agents, state_size=state_size, action_size=action_size,random_seed=2)

In [5]:
def maddpg_training(n_episodes=20000, max_t=1000, print_every=100):
    scores_deque = deque(maxlen=print_every)
    scores = []
    for i_episode in range(1, n_episodes+1):
        env_info = env.reset(train_mode=True)[brain_name]
        state = env_info.vector_observations
        maddpg_agent.reset()
        score = np.zeros(maddpg_agent.num_agents)
        for t in range(max_t):
            action = maddpg_agent.act(state)
            env_info = env.step(action)[brain_name]
            next_state = env_info.vector_observations 
            reward = env_info.rewards
            done = env_info.local_done
            maddpg_agent.step(state, action, reward, next_state, done)
            state = next_state
            score += np.array(reward)
            if any(done):
                break 
        scores_deque.append(np.max(score))
        scores.append(np.max(score))
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_deque)), end="")
        if i_episode % print_every == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_deque)))
        if np.mean(scores_deque)>=0.5:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode-100, np.mean(scores_deque)))
            for i, agent in enumerate(maddpg_agent.maddpg_agent):
                torch.save(agent.actor.state_dict(), 'checkpoint_actor_{}.pth'.format(i))
                torch.save(agent.actor_target.state_dict(), 'checkpoint_actor_target_{}.pth'.format(i))
                torch.save(agent.critic.state_dict(), 'checkpoint_critic_{}.pth'.format(i))
                torch.save(agent.critic_target.state_dict(), 'checkpoint_critic_target_{}.pth'.format(i))
                
            break
    return scores

scores = maddpg_training()

fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(np.arange(1, len(scores)+1), scores)
plt.ylabel('Score')
plt.xlabel('Episode #')
plt.show()

Episode 100	Average Score: 0.00
Episode 200	Average Score: 0.00
Episode 300	Average Score: 0.01
Episode 400	Average Score: 0.01
Episode 500	Average Score: 0.01
Episode 600	Average Score: 0.02
Episode 700	Average Score: 0.01
Episode 800	Average Score: 0.00
Episode 900	Average Score: 0.01
Episode 1000	Average Score: 0.03
Episode 1100	Average Score: 0.06
Episode 1200	Average Score: 0.07
Episode 1300	Average Score: 0.09
Episode 1400	Average Score: 0.10
Episode 1500	Average Score: 0.10
Episode 1600	Average Score: 0.12
Episode 1700	Average Score: 0.13
Episode 1800	Average Score: 0.30
Episode 1885	Average Score: 0.52

NameError: name 'scores_window' is not defined